replicaCount: 3

image:
  repository: ofriz/k8sproject
  tag: app-image-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8444

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

pvc:
  storage: 1Gi
ingress:
  host: nginx.local
