name: GitHub Secret
on: [push]
jobs:
  GitHub-Secrets:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use secret token
          env:
              TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          run: |
              echo "The GitHub Action Secret will be masked:  "
              echo ${{ secrets.TELEGRAM_TOKEN }}